2023-05-06 22:54:20,449 INFO    MainThread:21950 [wandb_setup.py:_flush():76] Current SDK version is 0.15.2
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_setup.py:_flush():76] Configure stats pid to 21950
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_setup.py:_flush():76] Loading settings from /home/colors/.config/wandb/settings
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_setup.py:_flush():76] Loading settings from /home/colors/Desktop/Cappuccino-Preparing-Robot-Baxter/colors-lab codes/train_scripts/wandb/settings
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'colors-lab codes/train_scripts/train.py', 'program': '/home/colors/Desktop/Cappuccino-Preparing-Robot-Baxter/colors-lab codes/train_scripts/train.py'}
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_init.py:_log_setup():507] Logging user logs to save/deneme1/wandb/run-20230506_225420-r5ala9g7/logs/debug.log
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_init.py:_log_setup():508] Logging internal logs to save/deneme1/wandb/run-20230506_225420-r5ala9g7/logs/debug-internal.log
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_init.py:init():547] calling init triggers
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'save_folder': 'save/deneme1', 'trainset_path': './train_dataset.pt', 'testset_path': './validate_dataset.pt', 'device': 'cpu', 'model': 'cnmp', 'in_shape': [7, 16], 'hidden_size': 256, 'num_hidden_layers': 2, 'weight_std': 1, 'min_std': 0.01, 'context_dims': [0, 1, 2, 3, 4, 5, 6], 'target_dims': [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], 'max_context': 300, 'max_target': 300, 'lr': 0.0001, 'batch_size': 20, 'max_iter': 200000, 'save_freq': 10000, 'test_freq': 10000, 'n_basis': 20, 'kernel_width': None, 'y_std': 0.1, 'amp': 1.0}
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_init.py:init():596] starting backend
2023-05-06 22:54:20,450 INFO    MainThread:21950 [wandb_init.py:init():600] setting up manager
2023-05-06 22:54:20,453 INFO    MainThread:21950 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-05-06 22:54:20,458 INFO    MainThread:21950 [wandb_init.py:init():606] backend started and connected
2023-05-06 22:54:20,463 INFO    MainThread:21950 [wandb_init.py:init():700] updated telemetry
2023-05-06 22:54:20,467 INFO    MainThread:21950 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-05-06 22:54:22,743 ERROR   MainThread:21950 [wandb_init.py:init():763] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2023-05-06 22:54:24,750 ERROR   MainThread:21950 [wandb_init.py:init():1168] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/home/colors/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
  File "/home/colors/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 769, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
